name: Deploy to Server

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 9001

      - name: Publish application
        run: |
          # Thêm máy chủ vào known_hosts nếu chưa làm
          ssh-keyscan -p 9001 -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

          # Xóa các file cũ trên server
          ssh -p 9001 ${{ secrets.USERNAME }}@${{ secrets.HOST }} "rm -rf ~/BE_Process_Exam_Manage/ExamProcessManage/publish/*"

          # Sao chép các file đã publish từ repository lên server
          scp -P 9001 -r ~/BE_Process_Exam_Manage/ExamProcessManage/publish/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/BE_Process_Exam_Manage/ExamProcessManage/publish/
